[build]
dockerfilePath = "apps/indexers/Dockerfile"
watchPatterns = [
  "apps/indexers/**",
  "packages/abis/**",
  "apps/protocol/broadcast/**",
  "apps/signals-token-factory/broadcast/**",
  "pnpm-lock.yaml",
  "pnpm-workspace.yaml",
  "apps/indexers/railway.toml",
]

[deploy]
startCommand = "pnpm start --schema deploy_$(date -u +%y%m%d_%H%M%S) --views-schema indexer"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
