[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.26'
evm_version = "cancun"
optimizer_runs = 1
via_ir = true
ffi = false

[fmt]
line_length = 100

[lint]
exclude_lints = [
    "unaliased-plain-import",
    "mixed-case-variable",
    "mixed-case-function",
]
