[profile.default]
optimizer_runs = 44444444
via_ir = true
ffi = true
solc = "0.8.26"
evm_version = "cancun"
gas_limit = "300000000"
bytecode_hash = "none"

[profile.debug]
via_ir = false
optimizer_runs = 200
fuzz.runs = 100

# Stack limit settings
stack_limit = 100_000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
arbitrumSepolia = { key = "${ARBISCAN_API_KEY}", chain = 421614 }
