name: Signals

on:
  push:
    paths:
      - 'apps/contracts/**'
  pull_request:
    paths:
      - 'apps/contracts/**'
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: rc

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge build
        working-directory: apps/contracts
        run: forge build --sizes
        id: build

      - name: Run Forge tests
        working-directory: apps/contracts
        run: forge test -vvv
        id: test
